#!/bin/bash
#########################################################
#							#
#	Script de autenticacao - Speedy Corp		#
# Desenvolvido por Fernando Augusto Medeiros Silva	#
#  (fams@linuxplace.com.br)				#
# Data: 17/05/2006					#
#							#
#########################################################

USERNAME="jadcargas@speedycorp.com.br" ### Coloque o seu #login aqui nesta variavel ###
PASSWORD="jaca";            ### Coloque aqui sua senha nesta variavel   ###

URL_TEST="200.176.3.142"; # \uffff necess\uffffrio retirar o "http://" da url
RET_TEST=`ping -c1 $URL_TEST |grep '100% packet loss'`; # Verifica conectividade com a internet

if [ -z "$RET_TEST" ];
then
        echo "J\uffff esta conectado !";
else
        echo "Conectando ...";
        curl -bJSESSIONID=issoeinutil "http://200.171.222.97:86//wsc/servlet/logon.do?opcion=internet&CPURL=&username=$USERNAME&password=$PASSWORD"
fi
