#!/bin/bash
# startup do vfailover
#
# chkconfig: 345 56 44
# description:  this script configure vfailover script
# config: /etc/vfailover.conf
. /etc/vfailover.conf
if [ $1 == "start" ];then
	if [ ! -z "$PRI_NET" ];then
		/sbin/ip route add $PRI_NET dev eth1 table $PRI_TABLE
	fi
	if [ ! -z "$PRI_GW" ];then
		/sbin/ip route add default via $PRI_GW table $PRI_TABLE
	fi
	if [ ! -z "$PRI_IP" ];then
		/sbin/ip rule add from $PRI_IP table $PRI_TABLE
	fi
	if [ ! -z "$PRI_MON" ];then
		/sbin/ip rule add to $PRI_MON table $PRI_TABLE
	fi
	if [ ! -z "$SEC_NET" ];then
		/sbin/ip route add $SEC_NET dev eth1 table $SEC_TABLE
	fi
	if [ ! -z "$SEC_GW" ];then
		/sbin/ip route add default via $SEC_GW table $SEC_TABLE
	fi
	if [ ! -z "$SEC_IP" ];then 
		/sbin/ip rule add from $SEC_IP table $SEC_TABLE
	fi
	if [ ! -z "$SEC_MON" ];then
		/sbin/ip rule add to $SEC_MON table $SEC_TABLE
	fi
fi
if [ $1 == "stop" ];then
	if [ ! -z "$PRI_NET" ];then
		/sbin/ip route del $PRI_NET dev eth1 table $PRI_TABLE
	fi
	if [ ! -z "$PRI_GW" ];then
		/sbin/ip route del default via $PRI_GW table $PRI_TABLE
	fi
	if [ ! -z "$PRI_IP" ];then
		/sbin/ip rule del from $PRI_IP table $PRI_TABLE
	fi
	if [ ! -z "$PRI_MON" ];then
		/sbin/ip rule del to $PRI_MON table $PRI_TABLE
	fi
	if [ ! -z "$SEC_NET" ];then
		/sbin/ip route del $SEC_NET dev eth1 table $SEC_TABLE
	fi
	if [ ! -z "$SEC_GW" ];then
		/sbin/ip route del default via $SEC_GW table $SEC_TABLE
	fi
	if [ ! -z "$SEC_IP" ];then
		/sbin/ip rule del from $SEC_IP table $SEC_TABLE
	fi
	if [ ! -z "$SEC_MON" ];then
		/sbin/ip rule del to $SEC_MON table $SEC_TABLE
	fi
fi
