#!/bin/sh
sed -e "/root/ s/ idxldapaccounts//" < /etc/webmin/webmin.acl > /etc/webmin/webmin.acl.new
mv /etc/webmin/webmin.acl /etc/webmin/webmin.acl.old
mv /etc/webmin/webmin.acl.new /etc/webmin/webmin.acl


