#!/bin/bash
touch /tmp/b
if [ "$PPP_IFACE" == "ppp0" ]; then
        /sbin/ip route flush table velox
        /sbin/ip route add $PPP_LOCAL dev $PPP_IFACE src $PPP_LOCAL table velox
        /sbin/ip route add default via $PPP_REMOTE table velox
        /sbin/ip rule add from $PPP_LOCAL table velox
#	/sbin/ip rule add fwmark 1 table velox
        #FIXME
        if [ ! -f /etc/shorewall/.rules.swp ]; then
                /sbin/shorewall restart > /dev/null
        fi
fi

